[package]
name = "resman_rustabi"
version = "0.0.1"
edition = "2021"

[lib]
name = "resman_rustabi"
crate-type = ["rlib"]

[dependencies]
libc = "0.2"
num_enum = "0.7"
core_rustabi = { path = "../core_rustabi" }
lowlevel_rustabi = { path = "../lowlevel_rustabi" }
