/* automatically generated by rust-bindgen 0.69.4 */

use super::*;

pub type StringArray = *mut ::std::os::raw::c_void;
pub type StringArrayConst = *const ::std::os::raw::c_void;
extern "C" {
    pub fn string_array_get_count(sa: StringArrayConst) -> usize;
    pub fn string_array_get_element(
        sa: StringArrayConst,
        index: usize,
    ) -> *const ::std::os::raw::c_char;
    pub fn string_array_free(sa: StringArray);
}
