[package]
name = "argus_scripting_lua"
version.workspace = true
edition.workspace = true

[lib]
name = "argus_scripting_lua"
crate-type = ["rlib"]

[dependencies]
argus_logging = { path = "../../libs/logging" }
argus_scripting_bind = { path = "../../libs/scripting_bind" }

argus_core = { path = "../core" }
argus_resman = { path = "../resman" }
argus_scripting = { path = "../scripting" }

lua = { path = "../../../external-bindings/lua" }

fragile = { workspace = true }
num_enum = { workspace = true }
parking_lot = { workspace = true }
