[package]
name = "scripting_lua_rs"
version = "0.0.1"
edition = "2021"

[lib]
name = "scripting_lua_rs"
crate-type = ["rlib"]

[dependencies]
argus_logging = { path = "../../libs/logging" }
argus_scripting_bind = { path = "../../libs/scripting_bind" }
core_rs = { path = "../../static/core_rs" }
resman_rs = { path = "../../static/resman_rs" }
scripting_rs = { path = "../../static/scripting_rs" }
lua = { path = "../../../external-bindings/lua" }
fragile = "2.0.0"
num_enum = "0.7.3"
parking_lot = "0.12.3"
