[package]
name = "scripting_lua_rs"
version = "0.0.1"
edition = "2021"

[lib]
name = "scripting_lua_rs"
crate-type = ["rlib"]

[dependencies]
argus_logging = { path = "../../libs/logging" }
argus_scripting_bind = { path = "../../libs/scripting_bind" }
scripting_rs = { path = "../../static/scripting_rs" }
core_rustabi = { path = "../../auxiliary/core_rustabi" }
resman_rustabi = { path = "../../auxiliary/resman_rustabi" }
lua = { path = "../../../external-bindings/lua" }
num_enum = "0.7.3"
parking_lot = "0.12.3"
