[package]
name = "sdl2"
version = "2.28.4"
edition.workspace = true
links = "SDL2"

[lib]
name = "sdl2"
crate-type = ["rlib"]

[dependencies]
bitflags = { workspace = true }
num_enum = { workspace = true }

[build-dependencies]
bindgen = { workspace = true }
