[package]
name = "argus"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[features]
default = ["opengl"]
opengl = ["argus_modules/opengl"]
vulkan = ["argus_modules/vulkan"]

[dependencies]
argus_modules = { path = "modules" }
