[package]
name = "sound_rs"
version = "0.0.1"
edition = "2021"

[lib]
name = "sound_rs"
crate-type = ["rlib"]

[dependencies]
argus_logging = { path = "../../libs/logging" }
core_rs = { path = "../../static/core_rs" }
wm_rs = { path = "../wm_rs" }
