[package]
name = "lua"
version = "2.28.4"
edition.workspace = true
links = "lua"

[lib]
name = "lua"
crate-type = ["rlib"]

[dependencies]

[build-dependencies]
bindgen = { workspace = true }
cc = {  version = "1.2.16", features = ["parallel"] }
