[package]
name = "ui_rs"
version = "0.0.1"
edition = "2021"

[lib]
name = "ui_rs"
crate-type = ["rlib"]

[dependencies]
argus_logging = { path = "../../libs/logging" }
core_rs = { path = "../../static/core_rs" }
input_rs = { path = "../input_rs" }
render_rs = { path = "../render_rs" }
resman_rs = { path = "../resman_rs" }
wm_rs = { path = "../wm_rs" }
