[package]
name = "input_rs"
version = "0.0.1"

[lib]
name = "input_rs"
crate-type = ["rlib"]
edition = "2021"

[dependencies]
sdl2 = { path = "../../../external-bindings/sdl2"}
argus_logging = { path = "../../libs/logging" }
argus_scripting_bind = { path = "../../libs/scripting_bind" }
lowlevel_rs = { path = "../../libs/lowlevel_rs" }
wm_rs = { path = "../wm_rs" }
lowlevel_rustabi = { path = "../../auxiliary/lowlevel_rustabi" }
core_rustabi = { path = "../../auxiliary/core_rustabi" }
resman_rustabi = { path = "../../auxiliary/resman_rustabi" }
bitmask = "0.5.0"
dashmap = "6.1.0"
lazy_static = "1.5.0"
num_enum = "0.7.3"
parking_lot = "0.12.3"
