[package]
name = "render_opengl_rust"
version = "0.0.1"
edition = "2021"

[lib]
name = "render_opengl_rust"
crate-type = ["rlib"]

[dependencies]
lazy_static = "1.5.0"
libc = "0.2"
num_enum = "0.7"
glslang = { path = "../../../external-bindings/glslang" }
spirv-cross-sys = { path = "../../../external-bindings/spirv-cross" }
argus_logging = { path = "../../libs/logging" }
argus_scripting_bind = { path = "../../libs/scripting_bind" }
core_rustabi = { path = "../../auxiliary/core_rustabi" }
lowlevel_rustabi = { path = "../../auxiliary/lowlevel_rustabi" }
lowlevel_rs = { path = "../../libs/lowlevel_rs" }
render_rs = { path = "../render_rs" }
wm_rs = { path = "../wm_rs" }
resman_rustabi = { path = "../../auxiliary/resman_rustabi" }
shadertools = { path = "../../libs/shadertools", default-features = false }
uuid = { version = "1.14.0", features = ["v4"] }

[build-dependencies]
arp = { git = "https://github.com/caseif/libarp-rs", rev = "78fed15", default-features = false }
