[package]
name = "render_rs"
version = "0.0.1"
edition = "2021"

[lib]
name = "render_rs"
crate-type = ["rlib"]

[dependencies]
argus_logging = { path = "../../libs/logging" }
argus_scripting_bind = { path = "../../libs/scripting_bind" }
lowlevel_rs = { path = "../../libs/lowlevel_rs" }
wm_rs = { path = "../wm_rs" }
lowlevel_rustabi = { path = "../../auxiliary/lowlevel_rustabi" }
core_rustabi = { path = "../../auxiliary/core_rustabi" }
resman_rustabi = { path = "../../auxiliary/resman_rustabi" }
dashmap = "6.1.0"
lazy_static = "1.5.0"
lodepng = "3.10.7"
num_enum = "0.7.3"
parking_lot = "0.12.3"
rgb = "0.8.50"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
uuid = { version = "1.14.0", features = ["v4"] }

[build-dependencies]
arp = { git = "https://github.com/caseif/libarp-rs", rev = "78fed15", default-features = false }
