[package]
name = "argus_render_vulkan"
version.workspace = true
edition.workspace = true

[lib]
name = "argus_render_vulkan"
crate-type = ["rlib"]

[dependencies]
argus_logging = { path = "../../libs/logging" }
argus_shadertools = { path = "../../libs/shadertools", default-features = false }
argus_util = { path = "../../libs/argus_util" }

argus_core = { path = "../core" }
argus_render = { path = "../render" }
argus_resman = { path = "../resman" }
argus_wm = { path = "../wm" }

ash = "0.38.0"
dashmap = "6.1.0"
glslang = "0.6.2"
itertools = { workspace = true }
konst = "0.3.16"


[build-dependencies]
arp = { workspace = true }
