[package]
name = "spirv-cross-sys"
version = "0.49.0"
edition.workspace = true

[lib]
name = "spirv_cross_sys"
crate-type = ["rlib"]

[dependencies]

[build-dependencies]
bindgen = { workspace = true }
