[package]
name = "resman_rs"
version = "0.0.1"
edition = "2021"

[lib]
name = "resman_rs"
crate-type = ["rlib"]

[dependencies]
arp = { git = "https://github.com/caseif/libarp-rs", rev = "52e8e02" }
dashmap = "6.1.0"
argus_logging = { path = "../../libs/logging" }
argus_scripting_bind = { path = "../../libs/scripting_bind" }
core_rs = { path = "../../static/core_rs" }
