name: Argus
on: [push, pull_request]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install libgl1-mesa-dev libgl1-mesa-glx libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
    - name: submodule checkout
      run: git submodule update --init --recursive
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Debug --parallel 8
    - name: archive
      uses: actions/upload-artifact@v1
      with:
        name: argus_dist_linux
        path: build/dist/

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: submodule checkout
      run: git submodule update --init --recursive
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_GENERATOR_PLATFORM=x64 ..
    - name: build
      run: cmake --build build --config Debug --parallel 8
    - name: archive
      uses: actions/upload-artifact@v1
      with:
        name: argus_dist_windows
        path: build/dist/
