name: Argus
on: [push, pull_request]
jobs:
  build-ubuntu-gcc-debug:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{secrets.ACCESS_TOKEN}}
        submodules: recursive
    - uses: ruby/setup-ruby@v1
      with:
        working-directory: external/tooling/aglet
        ruby-version: '3.0'
        bundler-cache: true
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libgl1-mesa-dev libgl1-mesa-glx libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libvulkan-dev
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
      env:
        CC: gcc
    - name: Build
      run: cmake --build build --config Debug --parallel 8
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: argus_dist_linux_debug
        path: build/dist/

  build-ubuntu-gcc-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: external/tooling/aglet
          ruby-version: '3.0'
          bundler-cache: true
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libgl1-mesa-dev libgl1-mesa-glx libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libvulkan-dev
      - name: Configure
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
        env:
          CC: gcc
      - name: Build
        run: cmake --build build --config Release --parallel 8
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: argus_dist_linux_release
          path: build/dist/

  build-ubuntu-clang-debug:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{secrets.ACCESS_TOKEN}}
        submodules: recursive
    - uses: ruby/setup-ruby@v1
      with:
        working-directory: external/tooling/aglet
        ruby-version: '3.0'
        bundler-cache: true
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libgl1-mesa-dev libgl1-mesa-glx libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libvulkan-dev
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
      env:
        CC: clang
        CXX: clang++
    - name: Build
      run: cmake --build build --config Debug --parallel 8
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: argus_dist_linux_debug
        path: build/dist/

  build-ubuntu-clang-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: external/tooling/aglet
          ruby-version: '3.0'
          bundler-cache: true
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libgl1-mesa-dev libgl1-mesa-glx libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libvulkan-dev
      - name: Configure
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
        env:
          CC: clang
          CXX: clang++
      - name: Build
        run: cmake --build build --config Release --parallel 8
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: argus_dist_linux_release
          path: build/dist/

  build-windows-debug:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{secrets.ACCESS_TOKEN}}
        submodules: recursive
    - uses: ruby/setup-ruby@v1
      with:
        working-directory: external/tooling/aglet
        ruby-version: '3.0'
        bundler-cache: true
    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.236.0
        vulkan-components: Vulkan-Loader, Glslang
        vulkan-use-cache: true
    - name: Configure
      run: mkdir build && cd build && cmake -G "Visual Studio 17" -DCMAKE_SYSTEM_VERSION=10.0.22621.963 -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=Debug ..
    - name: Build
      run: cmake --build build --config Debug --parallel 8
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: argus_dist_windows_debug
        path: build/dist/

  build-windows-release:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: external/tooling/aglet
          ruby-version: '3.0'
          bundler-cache: true
      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.236.0
          vulkan-components: Vulkan-Loader, Glslang
          vulkan-use-cache: true
      - name: Configure
        run: mkdir build && cd build && cmake -G "Visual Studio 17" -DCMAKE_SYSTEM_VERSION=10.0.22621.963 -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=Release ..
      - name: Build
        run: cmake --build build --config Release --parallel 8
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: argus_dist_windows_release
          path: build/dist/
