name: Argus
on: [push, pull_request]
jobs:
  build-ubuntu-gcc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{secrets.ACCESS_TOKEN}}
        submodules: recursive
    - uses: ruby/setup-ruby@v1
      with:
        working-directory: external/tooling/aglet
        ruby-version: '3.0'
        bundler-cache: true
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libgl1-mesa-dev libgl1-mesa-glx libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libvulkan-dev
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
      env:
        CC: gcc
    - name: Build
      run: cmake --build build --config Debug --parallel 8
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: argus_dist_linux
        path: build/dist/

  build-ubuntu-clang:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{secrets.ACCESS_TOKEN}}
        submodules: recursive
    - uses: ruby/setup-ruby@v1
      with:
        working-directory: external/tooling/aglet
        ruby-version: '3.0'
        bundler-cache: true
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libgl1-mesa-dev libgl1-mesa-glx libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libvulkan-dev
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
      env:
        CC: clang
        CXX: clang++
    - name: Build
      run: cmake --build build --config Debug --parallel 8
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: argus_dist_linux
        path: build/dist/

  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{secrets.ACCESS_TOKEN}}
        submodules: recursive
    - uses: ruby/setup-ruby@v1
      with:
        working-directory: external/tooling/aglet
        ruby-version: '3.0'
        bundler-cache: true
    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.204.1
        vulkan-components: Vulkan-Loader, Glslang
        vulkan-use-cache: true
    - name: Configure
      run: mkdir build && cd build && cmake -G "Visual Studio 16" -DCMAKE_SYSTEM_VERSION=10.0.19041.0 -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=Debug ..
    - name: Build
      run: cmake --build build --config Debug --parallel 8
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: argus_dist_windows
        path: build/dist/
