name: Argus
on: [push, pull_request]
jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
        compiler: [gcc, clang, msvc]
        configuration: [Release, Debug]
        exclude:
          - os: windows-2022
            compiler: gcc
          - os: windows-2022
            compiler: clang
          - os: ubuntu-22.04
            compiler: msvc
          - os: macos-12
            compiler: msvc
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set env vars for current matrix configuration
      shell: pwsh
      run: |
        $os_name = "${{ runner.os }}".ToLower()
        echo "OS_NAME=$os_name" >> "$env:GITHUB_ENV"

        $config_name = "${{ matrix.configuration }}".ToLower()
        echo "CONFIG_NAME=$config_name" >> $env:GITHUB_ENV

    - name: Update PATH
      shell: pwsh
      run: echo "${{ github.workspace }}/build/dist/lib" >> "$env:GITHUB_PATH"

    - name: Set env vars for GCC
      shell: pwsh
      run: |
        $suffix = if ("$env:OS_NAME" -eq "macos") { "-12" } else { "" }
          echo "CC=gcc$suffix" >> "$env:GITHUB_ENV"
          echo "CXX=g++$suffix" >> "$env:GITHUB_ENV"
      if: matrix.compiler == 'gcc'

    - name: Set env vars for Clang
      run: |
        echo "CC=clang" >> "$GITHUB_ENV"
        echo "CXX=clang++" >> "$GITHUB_ENV"
      if: matrix.compiler == 'clang'

    - uses: actions/checkout@v3
      with:
        token: ${{secrets.ACCESS_TOKEN}}
        submodules: recursive

    - uses: ruby/setup-ruby@v1
      with:
        working-directory: external/tooling/aglet
        ruby-version: '3.0'
        bundler-cache: true

    - name: Install dependencies (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install libgl1-mesa-dev libgl1-mesa-glx libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libvulkan-dev
      if: startsWith(matrix.os, 'ubuntu')

    - name: Setup Vulkan SDK (Windows)
      run: |
        $ver = (Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/latest.json" | ConvertFrom-Json).windows
        echo Version $ver
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$ver/windows/VulkanSDK-$ver-Installer.exe" -OutFile VulkanSDK.exe
        echo Downloaded
        .\VulkanSDK.exe --root C:\VulkanSDK  --accept-licenses --default-answer --confirm-command install
        echo "VULKAN_SDK=C:\VulkanSDK\" >> "$env:GITHUB_ENV"
      if: startsWith(matrix.os, 'windows')

    - name: Configure
      shell: pwsh
      run: |
        mkdir build
        cd build
        if ("$env:OS_NAME" -eq "windows") {
            cmake -G "Visual Studio 17" -DCMAKE_SYSTEM_VERSION=10.0.22621.963 -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} ..
        } elseif ("$env:OS_NAME" -eq "linux") {
            cmake -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} ..
        } elseif ("$env:OS_NAME" -eq "macos") {
            cmake -DCMAKE_BUILD_TYPE=${{matrix.configuration }} -DBUILD_VULKAN_BACKEND=OFF ..
        }

    - name: Build
      run: cmake --build build --config ${{ matrix.configuration }} --parallel 2

    - name: Run Tests
      working-directory: build
      run: ctest -C ${{ matrix.configuration }}

    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: argus_dist-${{ env.OS_NAME }}-${{ matrix.compiler }}-${{ env.CONFIG_NAME }}
        path: build/dist/
