[package]
name = "argus-trunk"
version = "0.0.1"
edition = "2021"

[package.metadata]
module-type = "static"

[build-dependencies]
cargo_metadata = "0.15"
lazy_static = "1.2"
regex = "1.6"

[lib]
name = "trunk"
crate-type = ["rlib"]

[dependencies]
argus-lowlevel = { path = "../../libs/lowlevel" }
ctrlc = "3.2"
lazy_static = "1.2"
static_init = "1.0"
libloading = "0.7"
