[package]
name = "core_rs"
version = "0.0.1"
edition = "2021"

[lib]
name = "core_rs"
crate-type = ["rlib"]

[dependencies]
arp = { git = "https://github.com/caseif/libarp-rs", rev = "52e8e02" }
dashmap = "6.1.0"
fragile = "2.0.0"
itertools = "0.14.0"
linkme = "0.3.28"
num_enum = "0.7.3"
parking_lot = "0.12.3"
argus_logging = { path = "../../libs/logging" }
argus_core_macros = { path = "../../libs/argus_core_macros" }
argus_scripting_bind = { path = "../../libs/scripting_bind" }
lowlevel_rustabi = { path = "../../auxiliary/lowlevel_rustabi" }
