[package]
name = "game2d_rs"
version = "0.0.1"

[lib]
name = "game2d_rs"
crate-type = ["rlib"]
edition = "2021"

[dependencies]
argus_scripting_bind = { path = "../../libs/scripting_bind" }
lowlevel_rustabi = { path = "../../auxiliary/lowlevel_rustabi" }
core_rustabi = { path = "../../auxiliary/core_rustabi" }
#scripting_rustabi = { path = "../../auxiliary/scripting_rustabi" }
resman_rustabi = { path = "../../auxiliary/resman_rustabi" }
wm_rustabi = { path = "../../auxiliary/wm_rustabi" }
input_rustabi = { path = "../../auxiliary/input_rustabi" }
render_rustabi = { path = "../../auxiliary/render_rustabi" }
lazy_static = "1.5.0"
num_enum = "0.7.3"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
serde_valid = "0.25.0"
uuid = { version = "1.11.0", features = ["v4"] }
